root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
 #"-dir=/mnt/seaweedVolume", , "-ip=go-api"
 #"-filer.port=8868" "-s3.port=8323"
  # args_bin = ["-v=1","server", "-volume.max=250", "-dir=/mnt/seaweedfs",  "-master.volumeSizeLimitMB=100", "-master.port=9333", "-filer.filerGroup=default", "-s3", "-s3.config","/etc/seaweedfs/s3.json", '-iam']
  # args_bin = ["-rf", "./tmp/main", "./tmp/weed", "&&", "chmod", "+x", "./tmp/weed", "&&", "sleep", "10000" ]
  # args_bin = [ "debug_server" ]

  # args_bin = ["docker-compose", "-f", "seaweedfs-dev-compose.yml", "restart"]
  # bin = "/usr/bin/cp"
  # bin = "/usr/bin/dlv"
  # cmd = "pkill -9 dlv "
  delay = 3000
  # exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec /usr/local/go/bin/go run ./weed -- server -v=1 -s3 -iam -ip=127.0.0.1 -dir=/mnt/sunfs -master.volumeSizeLimitMB=100 -master.defaultReplication=000 -filer.defaultReplicaPlacement=000 -volume.max=0 -iam.config=/home/sunteco/seaweed-camera/test/s3/iam/iam_config.local.json"
  # full_bin = "/usr/bin/sleep 100000"
  # full_bin="dlv exec ./tmp/main --listen=127.0.0.1:2345 --headless=true --api-version=2 --accept-multiclient --continue --log --"
  # build = "go build -o ./tmp/weed -tags='5BytesOffset rocksdb cassandra ydb sqlite foundationdb' -buildvcs=false ./weed"
  include_dir = ["weed"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "3s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  # post_cmd = ["kill  $(lsof -t -i :9333)", "kill  $(lsof -t -i :2345)"]
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
