#distrobox assemble
[alpine] # also inline comments are supported
additional_packages="yazi lazydocker"
image=docker.io/library/alpine:edge
init=true
# start_now=true
exported_bin="yazi"
# pull=true
root=false
replace=false
