version: '3.7'
services:
  go-api:
    hostname: go-api
    container_name: go-api
    # image: xuanquynguyen/seaweedfs:1.13-rocksdb_3.90
    # command:  ["-v=1","server", "-volume.max=250", "-dir=/mnt/seaweedfs",  "-master.volumeSizeLimitMB=100", "-master.port=9221", "-filer.filerGroup=default", "-s3", "-s3.config","/etc/seaweedfs/s3.json", '-iam']
    
    # network_mode: "host"
    image: cosmtrek/air
    build:
      context: .
      dockerfile: ./docker/Dockerfile.rocksdb_large_local_dev
      network: "host"
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - VOLUME_SPLIT_IN_SECONDS=60
      - GOTOOLCHAIN=auto
    # depends_on:
    #   - redis
    # ports:
    #   - 9333:9333
    #   - 8233:8333
    #   - 8085:8080
    #   - 8111:8111
    #   - 8888:8888 
    working_dir: /app
    volumes:
      - .:/app/
      # - ~/seaweedfs:/mnt/seaweedfs:rshared
      # - ./filer.toml:/etc/seaweedfs/filer.toml
      # - ./s3.json:/etc/seaweedfs/s3.json
      # - ~/rocksdb:/mnt/rocksdb
    networks:
      - net
  # haproxy:
  #   image: haproxy:2.4 # LTS version, until 2026
  #   container_name: haproxy
  #   restart: always
  #   # networks:
  #   #   - minio_app
  #   # network_mode: host
  #   # Add setting permission for open port 80 & 443 Require version kenel linux  >= 4.4, if else reading paragraph 7
  #   sysctls:
  #       - net.ipv4.ip_unprivileged_port_start=0
   
  #   volumes:
  #       - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  #       - /etc/localtime:/etc/localtime:ro
  #       # - ./haproxy/openssl.cnf:/etc/ssl/openssl.cnf:rshare
  #   ports:
  #       - 80:80
  #   networks:
  #       - net
networks:
  net: