version: '3.7'
services:
  go-api:
    hostname: go-api
    container_name: go-api
    network_mode: "host"
    # image: cosmtrek/air
    build:
      context: .
      dockerfile: ./docker/Dockerfile.rocksdb_large_local_dev
      network: "host"
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - VOLUME_SPLIT_IN_SECONDS=60
    # depends_on:
    #   - redis
    ports:
      # - 9333:9333
      - 8233:8333
      # - 8080:8080
      # - 8111:8111
      # - 8888:8888 
    # working_dir: /app
    volumes:
      - .:/app/
      # - ~/seaweedfs:/mnt/seaweedfs:rshared
      - ./filer.toml:/etc/seaweedfs/filer.toml
      - ./s3.json:/etc/seaweedfs/s3.json
      # - ~/rocksdb:/mnt/rocksdb
  # shell:
  #   container_name: seaweed-shell
  #   image: chrislusf/seaweedfs:3.84_large_disk_full
  #   command: "shell -master=go-api:9333 -filer=go-api:8888"
  # scylla:
  #   image: scylladb/scylla
  #   container_name: scylla
  #   command:  --memory 5G --overprovisioned 1 --api-address 0.0.0.0
  #   ports:
  #   - 9042:9042
    # - 9160:9160
    # - 6379:6379

    # volumes:
    #   - "./scylla.yaml:/etc/scylla/scylla.yaml"
  # redis:
  #   command: dragonfly  --logtostderr  --admin_nopass  --proactor_threads=1 --dir /mnt/dragonfly --maxmemory=3g 
  #   # --tiered_max_file_size 5GB --tiered_prefix /mnt/redisvol/tiered 
  #   environment:
  #   - REDIS_PORT=6379
  #   - REDIS_DATABASES=0
  #   hostname: redis
  #   volumes:
  #     - ./redis:/mnt/redisvol
  #     - ./redisbackup:/mnt/dragonfly

  #   image: docker.dragonflydb.io/dragonflydb/dragonfly
  #   ports:
  #   - 6379:6379
  #   restart: always
  #   ulimits:
  #     memlock: -1
  # redis-gui:
  #   image: redis/redisinsight:latest
  #   restart: always
  #   ports:
  #     - "5540:5540"
    
