version: '3.9'

services:
  master:
    image: chrislusf/rocksdb_dev_env
    # entrypoint: 'sleep 10000'   # use a remote dev image

    entrypoint: '/app/weed -v=1 master -ip=master -volumeSizeLimitMB=100 -volumePreallocate=false'   # use a remote dev image
    ports:
      - 9333:9333
      - 19333:19333
    # working_dir: /app 
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - VOLUME_SPLIT_IN_SECONDS=60
      - VOLUME_DELETION_INTERVAL_MILLISECONDS=300
      
    # command: "master -ip=master"
    volumes:
      # - ./tmp/weed:/usr/bin/weed
      - ./tmp:/app:rw
  admin:
    image: chrislusf/rocksdb_dev_env
    entrypoint: '/app/weed -v=1 admin -port=23646 -port.grpc=33646 -masters="master:9333"'   # use a remote dev image
    ports:
      - 23646:23646
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - VOLUME_SPLIT_IN_SECONDS=60
      - VOLUME_DELETION_INTERVAL_MILLISECONDS=300
      
    # command: "master -ip=master"
    volumes:
      # - ./tmp/weed:/usr/bin/weed
      - ./tmp:/app
  volume:
    image: chrislusf/rocksdb_dev_env      # use a remote dev image
    ports:
      - 8081:8080
      - 18080:18080
    entrypoint: '/app/weed -v=1 volume -mserver="master:9333" -port=8080 -ip=volume -ip.bind=0.0.0.0  -max=0 -dir=/mnt/volume'
    # -index=leveldbLarge
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - VOLUME_SPLIT_IN_SECONDS=60
      - INDEX_CACHE_IN_MB=64
      - VOLUME_DELETION_INTERVAL_MILLISECONDS=300
    volumes:
      # - ./tmp/weed:/usr/bin/weed
      - ./tmp:/app
      - ~/seaweedfs/v0:/mnt/volume
      
    depends_on:
      - master
  volume1:
    image: chrislusf/rocksdb_dev_env      # use a remote dev image
    ports:
      - 8082:8080
      - 18081:18080
    entrypoint: '/app/weed -v=1 volume -mserver="master:9333" -port=8080 -ip=volume1 -ip.bind=0.0.0.0  -max=0 -dir=/mnt/volume'
    # -index=leveldbLarge
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - VOLUME_SPLIT_IN_SECONDS=60
      - INDEX_CACHE_IN_MB=64
      - VOLUME_DELETION_INTERVAL_MILLISECONDS=300
    volumes:
      # - ./tmp/weed:/usr/bin/weed
      - ./tmp:/app
      - ~/seaweedfs/v1:/mnt/volume
      
    depends_on:
      - master
  filer:
    image: chrislusf/rocksdb_dev_env      # use a remote dev image
    ports:
      - 8888:8888
      - 18888:18888
      - 8333:8333
      - 8111:8111
    entrypoint: '/app/weed -v=5 filer -s3 -iam -master="master:9333" -ip.bind=0.0.0.0'
    volumes:
      - ./filer.toml:/etc/sunfs/filer.toml
      - ./s3.json:/etc/sunfs/s3.json
      # - ./tmp/weed:/usr/bin/weed
      - ./tmp:/app

      # - ~/filer/rocksdb1:/mnt/rocksdb
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - STORE_CACHE_IN_MB=64
    depends_on:
      - master
      - volume
  # filer2:
  #   image: chrislusf/rocksdb_dev_env # use a remote dev image
  #   ports:
  #     - 8887:8888
  #     - 18887:18888
  #   command: '/app/weed -v=1 filer  -s3 -iam -master="master:9333" -ip.bind=0.0.0.0'
  #   volumes:
  #     - ./filer.toml:/etc/sunfs/filer.toml
  #     - ./s3.json:/etc/sunfs/s3.json
  #     - ./bin:/app
  #     # - ~/filer/rocksdb2:/mnt/rocksdb
  #   environment:
  #     - TZ=Asia/Ho_Chi_Minh
  #   depends_on:
  #     - master
  #     - volume
  # s3:
  #   image: chrislusf/rocksdb_dev_env # use a remote dev image
  #   ports:
  #     - 8333:8333
  #   entrypoint: '/app/weed -v=1 s3 -filer="filer:8888" -ip.bind=0.0.0.0'
  #   environment:
  #     - TZ=Asia/Ho_Chi_Minh
  #   volumes:
  #     - ./filer.toml:/etc/sunfs/filer.toml
  #     - ./s3.json:/etc/sunfs/s3.json
  #     # - ./tmp/weed:/usr/bin/weed
  #     - ./tmp:/app
  #   depends_on:
  #     - master
  #     - volume
  #     - filer
  # webdav:
  #   image: chrislusf/seaweedfs:dev # use a remote dev image
  #   ports:
  #     - 7333:7333
  #   command: 'webdav -filer="filer:8888"'
  #   depends_on:
  #     - master
  #     - volume
  #     - filer
