FROM chrislusf/rocksdb_dev_env as builder

# build SeaweedFS
# RUN mkdir -p /go/src/github.com/seaweedfs/
# ADD . /go/src/github.com/seaweedfs/seaweedfs
# RUN ls -al /go/src/github.com/seaweedfs/ && \
#   cd /go/src/github.com/seaweedfs/seaweedfs/weed \
#   && export LDFLAGS="-X github.com/seaweedfs/seaweedfs/weed/util.COMMIT=$(git rev-parse --short HEAD)" \
#   && go install -tags "5BytesOffset rocksdb elastic gocdk rclone sqlite tikv ydb" -ldflags "-extldflags -static ${LDFLAGS}"
RUN cd /
RUN curl -sSfL https://raw.githubusercontent.com/air-verse/air/master/install.sh | sh -s -- -b /usr/bin
# FROM alpine AS final
# LABEL author="Chris Lu"
# COPY --from=builder /go/bin/weed /usr/bin/
# COPY --from=builder /bin/air /usr/bin/

# RUN mkdir -p /etc/seaweedfs
# COPY --from=builder /go/src/github.com/seaweedfs/seaweedfs/docker/filer_rocksdb.toml /etc/seaweedfs/filer.toml
# COPY --from=builder /go/src/github.com/seaweedfs/seaweedfs/docker/entrypoint.sh /entrypoint.sh
# RUN apk add fuse snappy gflags tmux

# volume server gprc port
EXPOSE 18080
# volume server http port
EXPOSE 8080
# filer server gprc port
EXPOSE 18888
# filer server http port
EXPOSE 8888
# master server shared gprc port
EXPOSE 19333
# master server shared http port
EXPOSE 9333
# s3 server http port
EXPOSE 8333
# webdav server http port
EXPOSE 7333

RUN mkdir -p /data/filer_rocksdb

# VOLUME /app/

WORKDIR /app

RUN chmod +x /bin/air

ENTRYPOINT ["/usr/bin/air"]
